excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://QuickBFox.github.io
title: Quick B. Fox
tagline: My worlds
description: Site to keep and organize my RPG adventures
paginate: 5
